### ISSUE TITLE
Default to Java 17 in samples

### ISSUE THREAD

**Issue by johanandren** [lightbend/kalix-jvm-sdk#1144]
We support Java 11 and 17, the samples default to JDK 11, is there a reason or shouldn't we bump the samples to JDK 17 since that is the current LTS (even if we support 11 as well)?

**Comment by beritou** [comment]
+1 to bumping samples to JDK 17. @kumrahul16 any reason we shouldn't?

**Comment by octonato** [comment]
For the record, we bump the version for the Spring samples today. 

The reason is that Java 17 has records and sealed interfaces which makes it much more convenient and clean to defined immutable models. And we always recommend immutable models. 

We can revert to Java 11 eventually, but we can let it for the users to decide to downgrade to 11 if they need to. 

One issue that comes to mind is what to do with the build. Should be start to run tests for both JDKs?

**Comment by kumrahul16** [comment]
> +1 to bumping samples to JDK 17. @kumrahul16 any reason we shouldn't?

Nothing that I'm aware of, should be okay I guess. We don't have a customer using it to weigh in. I think we should be good.

**Comment by ennru** [comment]
We're in a good state here.
