### ISSUE TITLE
Java code-first SDK: support for Akka's Jackson migration

### ISSUE THREAD

**Issue by octonato** [lightbend/kalix-jvm-sdk#1332]

**Comment by efgpinto** [comment]
I was doing some experiments mainly for my own understanding of what was possible already or not, so here are some notes here:
- add/removing fields from state types seems mostly fine: the fields will be `null` when non-existing and logic to handle that needs to live on the UF.
- class renaming is fine as long as structure matches new type (or type info is used for ES events)

Akka Jackson migration will be needed to:
- support renaming fields
- support transforming fields and changing type (works for some primitive type conversions but fails for composite ones as expected)

**Comment by octonato** [comment]
Json behaves similar to proto with respect to unknown fields. The main issue is renaming indeed. 

Renaming is no issue for gRPC, only ordering matters. Changing type is a major problem for gRPC as well. And I don't think we should even try to solve this kind of problems. 

Good that Akka Jackson Migration have already some support for it, even if limited that's already something. We are fine as long as we document the limitations. 

Speaking about documenting migration, I don't think we have anything about protobuf and we simply expect that users will know how to evolve their protobuf. That's probably too optimistic. 

I hear often that schema evolution is not an issue for protobuf. That's true only if you know what you are doing. The reality, is that very often people change their format without much care.

**Comment by johanandren** [comment]
Side note: Re the protobuf schema evolution, we don't really link to it from our docs (we should), but there is information in the protobuf documentation: https://protobuf.dev/programming-guides/proto3/#updating

**Comment by aludwiko** [comment]
Ok, I'm experimenting with a similar approach to Akka Jackson Migration. The biggest challenge is how to save the version number. My idea is to use the `typeUrl` for that, e.g. `json.kalix.io/com.example.SimpleClass#1` after hash I will add the version number. So far it looks promising, but if you see any blockers, please let me know:)

**Comment by aludwiko** [comment]
One interesting thing about Views + Migration is that we can now support the schema evolution of VE state model. For instance, we could have:
```
public class CustomerEntity extends ValueEntity<Customer> 
```
after some time this could be changed to:
```
@Migration(CustomerUpdatedMigration.class)
public record CustomerUpdated()
...
public class CustomerEntity extends ValueEntity<CustomerUpdated> 
```

A view can be created with a dummy transformation, that just returns the deserialized state, and the `CustomerUpdatedMigration` will do the job on the fly.

```
public class CustomerByEmailView extends View<CustomerUpdated> {
  @Subscribe.ValueEntity(CustomerEntity.class)// <3>
  public UpdateEffect<CustomerUpdated> transform(CustomerUpdated customer) {
    return effects().updateState(customer);
  }
}
```

**Comment by aludwiko** [comment]
Ok, so `@TypeName` would work out of the box for all cases. For entities state it actually does matter. The type is always from the Java generics. As long the JSON schema is the same, the decoding will work. With workflows, the situation is a bit different, because we are persisting also step inputs and outputs, so we could emphasize thinking about ser/der more.

**Comment by aludwiko** [comment]
Another interesting observation. Let's say we have a Wallet Entity:
```
public class WalletEntity extends ValueEntity<WalletEntity.Wallet> {

   @JsonTypeInfo(use = JsonTypeInfo.Id.NAME)
  @JsonSubTypes({
      @JsonSubTypes.Type(value = WithdrawResult.WithdrawSucceed.class),
      @JsonSubTypes.Type(value = WithdrawResult.WithdrawSucceed.class)})
  public sealed interface WithdrawResult {
    record WithdrawFailed(String errorMsg) implements WithdrawResult {
    }

    record WithdrawSucceed() implements WithdrawResult {
    }
  }


  @PatchMapping("/withdraw/{amount}")
  public Effect<WithdrawResult> withdraw(@PathVariable int amount) {
    Wallet updatedWallet = currentState().withdraw(amount);
    if (updatedWallet.balance < 0) {
      return effects().reply(new WithdrawFailed("Insufficient balance"));
    } else {
      return effects().updateState(updatedWallet).thenReply(new WithdrawSucceed());
    }
  }
  ```
  
  and we are calling the `withdraw` endpoint from the same service. In that case, we don't need any `@JsonSubTypes` annotations, because the `Any.urlType` gives us all the information required to deserialize such a payload. Unless we transform the deferred call to a `CompletionStage`:
  ```
              componentClient.forValueEntity(cmd.from)
              .call(WalletEntity::withdraw)
              .params(cmd.amount).execute()
   ```
   
If so, the deserialization is done via Spring Web Client internals without (our) `JsonSupport`utility. Here `@JsonSubTypes` is required to produce a proper payload and to deserialize it later. 
   
If we do the same, but the call will be to an external Kalix service. Not only should we recommend using `@TypeName` annotation, but also `@JsonSubTypes` annotation with hardcoded type name:
```
@JsonSubTypes.Type(value = WithdrawResult.WithdrawSucceed.class, name = "withdraw-succeed"),
```
to avoid sending FQCN. We are talking about mixed usage: rest calls + deferred calls.
