### ISSUE TITLE
Spring SDK JSON responses do not include int 0 or boolean false values 

### ISSUE THREAD

**Issue by mckeeh3** [lightbend/kalix-jvm-sdk#1359]
This is problematic in JS because references to these fields have `undefined` values.

**Comment by efgpinto** [comment]
Some more details here are, it happens only when query views... If you query the entity directly, all that is there but when querying a view, some info is missed, e.g.

> curl -H "Content-type: application/json" localhost:9000/customer/two
```json
{"customerId":"one","email":"test@example.com","name":"Test Testsson","address":{"street":"Teststreet 25","city":"Testcity","recent":false,"lat":0.0,"lng":0.0},"married":false,"age":0.0}% 
```

The same entity retrieved from a view (note that `married`, `lat`, `lng` and `age` are missing for the second record `two` but `married` appears on the first because is not `false`):
> curl localhost:9000/wrapped/by_name/Test%20Testsson
```json
{
  "customers": [{
    "customerId": "one",
    "email": "test@example.com",
    "name": "Test Testsson",
    "address": {
      "street": "Teststreet 25",
      "city": "Testcity"
    },
    "married": true
  },{
    "customerId": "two",
    "email": "test@example.com",
    "name": "Test Testsson",
    "address": {
      "street": "Teststreet 25",
      "city": "Testcity"
    }
  }]
}

**Comment by johanandren** [comment]
Renato is on it, but for the record the problem is that in views we have to parse the view row into protobuf to project into a different format, and in protobuf primitive default values are omitted, so a missing flag in our rendering of that projected protobuf into json telling it to include default values.
