### ISSUE TITLE
High level API for setting _kalix-http-code

### ISSUE THREAD

**Issue by jroper** [lightbend/kalix-jvm-sdk#1851]
We should expose a method on `Metadata` to set the HTTP response code when using HTTP transcoding, without having to rely on the internal `_kalix-http-code` name. ie:

```java
/**
 * Set the HTTP response code for the response.
 *
 * This will only take effect when HTTP transcoding is in use. It will be ignored for gRPC requests.
 */
public Metadata withHttpResponseCode(int code) {
  if (code < 200 || code > 599) {
    throw new RuntimeException("Invalid HTTP status code: " + code);
  }
  return set("_kalix-http-code", code.toString());
}
```

**Comment by efgpinto** [comment]
We should probably move forward with this.. We have had multiple users making use of our internal header which is not ideal. Another [example](https://kalixworld.slack.com/archives/C05CBK0VCKH/p1702323429975409).

**Comment by octonato** [comment]
Somewhat related to https://github.com/lightbend/kalix-jvm-sdk/issues/1639

**Comment by efgpinto** [comment]
I think the strategy might be slightly different between code-first and protocol-first sdks.

For protocol-first a simple method on the Metadata as shown above could be enough, since users might not even be using HTTP, they don't need to be exposed to it by default (which would happen if we allowed to pass the status code directly in a new `reply()´ method overload or in specific methods `replyNoContent()`).

For code-first I think there will be a need for a different API, one that maybe not only allows you to define the HTTP code but maybe some associated data (e.g. when setting 301 as return code I should probably set a value for a "Location" header as well). Should this be done leveraging the existing Spring specific classes (e.g. ResponseEntity, ResponseStatus) or using internal ones that could be reused for scala code-first in the future? This is a similar discussion to what we are doing [here](https://github.com/lightbend/kalix-jvm-sdk/issues/1639).

I'm tempted to implement the simpler helper method which can be used in both protocol-first and code-first SDK as a quicker way to move users off using our internal header directly. As for the long term solution, I think we will still need to discuss further.

**Comment by efgpinto** [comment]
Also discovered today that no only Spring users use the `ResponseEntity` to set the status code, but they can also shortcut it with `ResponseCode` at method, class and exception level (see [here](https://www.baeldung.com/spring-response-status)). Seemed like an annotation we could potentially support as well to please people coming from Spring background.

**Comment by octonato** [comment]
Ideally, the Java SDK should be independent of any framework. We initially made it strong Spring biased, but as of today, Spring is just a shell where we run the user services.

We do have a Spring ApplicationContext of course (part of that shell) and we do hook into Spring to make it work, but we should keep its dependency to a minimal. 

Also, we don't want to have the Effect API depending on any Spring class as it is at the core of the JVM SDKs (also Java and Scala Protobuf). 

From the user perspective, they build the components using Effects, so it's ok to not expect Spring APIs at that level, IMO.

For the `@ResponseCode` annotation, that could be an addition to the Spring shell that is then translated to the Effect API equivalent behind the scenes. But I wouldn't consider it a priority for now.

**Comment by efgpinto** [comment]
We now have the API that allows clients to not depend on the internal header so I'm closing this one. Related discussion around an higher-level API for responses continue on https://github.com/lightbend/kalix-jvm-sdk/issues/1639 .
