### ISSUE TITLE
Support Envoy Validation for Scala Protobuf projects

### ISSUE THREAD

**Issue by reid-spencer** [lightbend/kalix-jvm-sdk#695]
In my use of akka-grpc api development (besides Akka Serverless) we have become accustomed to using the ScalaPB validation library.  This really helps to communicate the semantics of the data fields in an API. Details on that are here: 
* https://scalapb.github.io/docs/validation

I tried to add this to my project but was only able to mess up the Scala code generation (generated code doesn't compile, missing references, duplicate code).  I believe that this should be pretty straightforward to provide in conjunction with Akka Serverless, but the existing installation instructions from ScalaPB (https://scalapb.github.io/docs/validation#installation) don't work directly.  It would be nice if this became an option on the Akka Serverless plugin or at least there was documentation about how to configure the ScalaPB validation feature with Akka Serverless.

**Comment by johanandren** [comment]
I agree that being able to define declarative validation in the proto definition would be neat, I wonder though if it should rather be one step away from the SDK so that Akka Serverless already performs such validation of incoming requests without the SDK itself needing to generate any additional ScalaPB logic (this would also provide the same validation for all SDKs, not only Scala). 

@jroper @retgits anything we've considered before?

**Comment by reid-spencer** [comment]
@johanandren - You wrote:
>  so that Akka Serverless already performs such validation of incoming requests without the SDK itself needing to
> generate any additional ScalaPB logic

Are you trying to say that Akka Serverless has some magical AI built-in so that when I have something like:
```protobuf
message Foo {
  string phoneNumber = 1;
}
```
that it can intuit that when a Foo is received that it parses the string in the phoneNumber value, it can ensure that the data value is a phone number with no further indication of its intended format?  ;->

I strongly doubt this and even if it did, this would be a reason to reject Akka Serverless as a solution because it is likely to interpret the domain of the solution incorrectly.  

Since the code generation is already handled by ScalaPB into separate files, simply enabling it doesn't seem like a lot of work.  

I am working on a PR, but my time is compromised by other things.  It seems to me like a small request and optional at that.

**Comment by pvlugter** [comment]
> > so that Akka Serverless already performs such validation of incoming requests without the SDK itself needing to
> > generate any additional ScalaPB logic
> 
> Are you trying to say that Akka Serverless has some magical AI built-in

Not expected to be magical, it would be the user adding the validation annotations to the protobuf, and then rather than code generation or an SDK validating, the Akka Serverless proxy could dynamically validate requests based on the annotated rules. This would then be supported for all language SDKs, and wouldn't require any extra build configuration.

Allowing ScalaPB generated validation to be enabled should also be possible.

**Comment by jroper** [comment]
The "ScalaPB validation" support being requested here actually is not ScalaPB validation, it's envoy validation, the validation annotations come from envoy:

https://github.com/envoyproxy/protoc-gen-validate

ScalaPB does provide an implementation of this validation itself, but, the point is, if we want to support this, which we do, we want to support it for all languages, not just Scala. And because we have a proxy that all the messages pass through, and because that proxy knows and has a deep understanding of the protobuf messages that pass through it and in particular those messages descriptors with their annotations, we can provide support for this in the proxy. And if we provide support in the proxy, then we only have to implement support for it once, and all languages get it.

**Comment by reid-spencer** [comment]
@jroper - That sounds even better!

**Comment by johanandren** [comment]
Seems like it is currently possible to "just" use the validations on the Scala side, without any support in the proxy, might be a less complex path for now, even if it isn't the long term solution.

Since there is no special handling turning those validation errors into bad request responses (`scalapb.validation.FieldValidationException` is one) it is handled like any other internal/unexpected error, logged and an error response with the correlation id is returned to the client.

I think that could be handled in the SDK deserialization or the router calling that, looks like it is thrown from the user generated scalapb message factory invoked in `AnySupport.decodeMessage`.

**Comment by johanandren** [comment]
Change of direction again, after some contemplating and discussing we have arrived at that it is best to support this natively for each SDK, I have created a PR to support Scala / ScalaPB to start with.
