### ISSUE TITLE
updateContext and actionConext support for event timestamp

### ISSUE THREAD

**Issue by aklikic** [lightbend/kalix-jvm-sdk#889]
Many use cases require `events` to have  `entity ID` and `timestamp`. 
Currently it is possible to access `entity ID` via `updateContext` and `actionContext` (`eventSubject()`) so it is not explicitly required to have entity ID in the event data structure itself. 
Would it be possible to expose, in the similar way, underlying `event timestamp`?

**Comment by jroper** [comment]
Does `ctx.metadata().asCloudEvent().time()` not work?

**Comment by aklikic** [comment]
Yes it does. Was not aware of this option. Thank you. 
Is this somewhere in the docs?

**Comment by jroper** [comment]
Did you actually try it? I just had a look at the proxy code and it appears that the `time` field isn't populated either for event sourced events, or value entity events, probably due to limitations in what metadata is available from Akka persistence.

No it's not documented. We should have a page on CloudEvents and how CloudEvents are used in Akka Serverless.

**Comment by aklikic** [comment]
Yea, did not test it, just validated I can access it. 
So there is no underlying timestamp because Akka persistance does not provide it?

**Comment by jroper** [comment]
Correct.

**Comment by patriknw** [comment]
We have a timestamp in the EventEnvelope that is used in Akka Projection. Maybe that is lost in translation, but should be possible to include.

**Comment by jroper** [comment]
Good to know, we should add it.

**Comment by aludwiko** [comment]
I think we can close, fixed on the proxy side: https://github.com/lightbend/kalix-proxy/issues/1327
