### ISSUE TITLE
Spring RestControllers and Actions

### ISSUE THREAD

**Issue by octonato** [lightbend/kalix-jvm-sdk#993]
References https://github.com/lightbend/kalix/issues/6859

I have been thinking about how we could best integrate Spring RestControllers and Actions and I came up with the following idea. Submitting here for early feedback (cc @jroper / @johanandren). 

In the Spring SDK, we could take a slight different approach and decide that all components are private and only accessible from inside the service. 
Then, we let users use explicitly Spring RestControllers to define the external API. For example: 

```java
@RestController
public class GreetingController {

  private static final String template = "Hello %s!";

  @GetMapping("/greeting")
  public Greeting greeting(@RequestParam(value = "name", defaultValue = "World") String name) {
    return new Greeting(String.format(template, name));
  }
}
```

Users will be able to inject a Component Ref in that same controller and do forward or direct calls to the entity. 

A Component Ref would be something similar to the current component clients we have. We can use annotation processors to generate them. They will have a similar API, but instead of returning Effects, the will return a DeferredCall. Executing a deferred call in place, will return a `Mono`. 

Note that we should not allow the injection of components directly. It should always be its `Ref`. And since there is a 1:1 with the component, we can throw an exception saying: "You should inject WhateverComponentNameRef instead".

So, the Rest Controllers will act like an "Action as Controllers". In the background, we generate an Action descriptor for it. 

For example:

```java
@RestController
public class GreetingController {

  private static final String template = "Hello %s!";

  private HelloEntityRef helloEntity; // Not HelloEntity but it's generated companion returning DeferredCall / Mono
  
  public GreetingController(HelloEntityRef helloEntity) {
    this.helloEntity	= helloEntity;
  }

  @GetMapping("/greeting")
  public DeferredCall<String, Greeting> greeting(@RequestParam(value = "name", defaultValue = "World") String name) {
    return helloEntity.sayHello(name); // like forwarding
  }

  @GetMapping("/greeting")
  public Mono<Greeting> greeting2(@RequestParam(value = "name", defaultValue = "World") String name) {
    return helloEntity.sayHello(name).execute(); // calling directly in order to map/flatMap
  }
}
```

For the other user cases, users will have to use Actions without REST annotations. That means that Actions used for subscribing and publishing are for internal and are not exposed. 

All generated proto descriptors that the SDK produces, will have the ACL restricted to internal. Except the 'Action' one that we derive from `RestController`

**Comment by jroper** [comment]
We probably won't be able to use `@RestController` as Spring boot will likely want to expose that as a servlet based REST API, we'd have to use our own annotation.

My biggest concern with this is that it may be too far removed from the Kalix architecture that we want to expose to users.

There is a big advantage to requiring actions to invoke entities by their public interfaces - it makes it clear that this is a call that may well be going over the network. I know Renato you mentioned that that may be unnatural to a Spring user, but there are some aspects of Kalix that we want to be unnatural precisely because they are fundamental architectural concepts that we want users to learn. We don't want to hide Kalix's fundamental architecture as if it's magic. We want users to understand it.

So, hiding gRPC is fine, since gRPC has nothing to do with our core architecture, it's really an implementation detail. But hiding the fact that entities themselves are deployed, sharded across the cluster, and making them appear instead as things that operate completely internally to a service, that's contrary to our core architecture.

Of course, by default, entities should not be publicly accessible, we should require users to add a @KalixAcl annotation to their services to expose them. But I think when we introduce the concept of entities to users, users should understand them to be things that are inherently exposed across the network because they are sharded. Entities are a first class architectural concept deployed to nodes on the network, not a design detail of a service sitting behind it's public interface. And requiring users to explicitly define a remote interface for that, whether it be REST, gRPC, or whatever other transports we want to support (maybe Spring users would like RMI? Nah...), and requiring them to invoke those components via that remote interface, I think is a very powerful tool for reinforcing that point.

**Comment by jroper** [comment]
Another thing is that I think deploying multiple components in a single service should be something that's just an optimisation - both performance-wise, it avoids a network hop, as well as organisationally-wise, as it's more efficient to develop and operate in one service than to spread it across multiple services. But, I think it should be trivial to split these out into their own services at any time, with the only thing needed to be done is to set some ACLs so that only the newly split out service can invoke the entity, and updating routes if any part of the service is exposed to the internet.

We still are calling Kalix a serverless offering, and I think keeping entities as their own independently deployable units is an important part of that.

**Comment by patriknw** [comment]
> In the Spring SDK, we could take a slight different approach and decide that all components are private and only accessible from inside the service.

I don't understand the reason why we wouldn't support HTTP API (REST) directly on the entity components and require actions (controllers) in all cases? As James says, entities is the very core model in Kalix and it's in many cases convenient to be able to expose the entity directly without an additional action layer.

**Comment by octonato** [comment]
> We probably won't be able to use `@RestController` as Spring boot will likely want to expose that as a servlet based REST API, we'd have to use our own annotation.

I think it's worth investigating it further. In the PR I put out, i disabled the Spring Boot server (tomcat), so there is not servlet being exposed. When the application starts, it's our akka http that starts. 

> My biggest concern with this is that it may be too far removed from the Kalix architecture that we want to expose to users.
> 
> There is a big advantage to requiring actions to invoke entities by their public interfaces - it makes it clear that this is a call that may well be going over the network. I know Renato you mentioned that that may be unnatural to a Spring user, but there are some aspects of Kalix that we want to be unnatural precisely because they are fundamental architectural concepts that we want users to learn. We don't want to hide Kalix's fundamental architecture as if it's magic. We want users to understand it.

My point was not about being unnatural to Spring users, it's unnatural for everybody. We changed Kalix to use DeferredCall because we wanted a typed API, but also because it's very weird define things in my project, using a typed language, by not being able to call it. And we don't allow it, we use the component clients. But at least we offer a path for the users. 

So, what is the different of using 

in current Kalix
```java
components.shoppingCart.addItem(Item(...)) // returns DeferredCall
```
in the new proposal

```java
shoppingCartRef.addItem(Item(..)) // returns DeferredCall
```

Why the former is not hiding the fundamental architecture of Kalix and the latter is? I see absolutely no different. 

Using a component client / component ref we are also telling the users: look, that entity that we define here, it's not something that you can simply access. That's something managed by Kalix and you have to go through this thing we are offering you. 


> So, hiding gRPC is fine, since gRPC has nothing to do with our core architecture, it's really an implementation detail. But hiding the fact that entities themselves are deployed, sharded across the cluster, and making them appear instead as things that operate completely internally to a service, that's contrary to our core architecture.

I don't think that I was suggesting to make it completely transparent. My suggestion is not different than the existing status-quo.

>  users should understand them to be things that are inherently exposed across the network because they are sharded. 

I think it's own our interested that users understand that entities are managed by Kalix and access to it should be through what Kalix offers. That's why we should absolutely block the injection of components. Because it simply don't work.
The fact that entities are sharded should not be a user concern. They can read about it, they can learn if they want, but the beauty of Kalix is exactly that they don't need to even think about it, because we give them the right level of abstraction.

**Comment by octonato** [comment]
> > In the Spring SDK, we could take a slight different approach and decide that all components are private and only accessible from inside the service.
> 
> I don't understand the reason why we wouldn't support HTTP API (REST) directly on the entity components and require actions (controllers) in all cases? As James says, entities is the very core model in Kalix and it's in many cases convenient to be able to expose the entity directly without an additional action layer.

I don't think that the fact that is a core model means that it should be easily exposed. If we take any classical application out there, we can also argue that the JPA/Hibernate model is the core of the application where the business logic resides. Then, to access it, people add Controllers / Services in front.

**Comment by johanandren** [comment]
With JPA you _need_ a controller in front, because the mapped classes themselves does not provide any way to query or mark the completion of a transaction, so that is different from Kalix where you address by id to load and the entities themselves decide when to write.

I definitely think that not having to front entities with an intermediate layer/controller is a big benefit of Kalix.

**Comment by jroper** [comment]
> And expose your domain to the outside? Is that the best-practice that we want to promote?

Yes, it is. This is what serverless is. What you deploy in serverless is not completely packaged services with a public, internet accessible API and opaque internals. You deploy components, which get wired together using network protocols.

I actually think we want to discourage our users from using the action in front of entity pattern. This isn't MVC. We don't want our users to think of it as MVC. It's serverless, it's stateful serverless, really, it's actors. Actors get communicated with over the network. You don't put a REST controller in front of an actor for other actors to communicate with it, actors communicate with each other directly through addressed messaging.

We may have components that act as controllers, but controllers should not live inside Kalix services, they should be separate components that get deployed. The Kalix project is one big logical application. The services deployed to it, they are the components. Not things running inside the services, the services themselves are, conceptually, the components.

**Comment by jroper** [comment]
I understood the meaning of calling it `*Ref`, but that's only because I understand actors and Akka. Our target audience won't.

**Comment by octonato** [comment]
So, is that what you mean when you said that we could give the impression that we are calling the real thing? If that's the case, we can call it `*Client`. We are not doing so with the current component clients, we just use the name of the component. 

Anyway, this is not urgent thing and we see later how we will do components calls. The annotation processors could be an extra dependency that users could add themselves. We can throw it out as an experimental addon and see if users pick it or not.

**Comment by octonato** [comment]
Closing is as most of this have been discussed and settled. We still need to decide how to deal with deferred call, but there is an specific issue for that. 

https://github.com/lightbend/kalix/issues/7370
